# Generated by Django 6.0.3 on 2026-03-18 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('resourcetype', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=200)),
                ('capacity', models.IntegerField()),
                ('status', models.CharField(max_length=20)),
                ('availableSchedule', models.JSONField()),
            ],
        ),
    ]
