# Generated by Django 6.0.3 on 2026-03-20 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0003_alter_resource_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='resourcetype',
        ),
        migrations.AlterField(
            model_name='resource',
            name='status',
            field=models.CharField(choices=[('activo', 'ACTIVO'), ('inactivo', 'INACTIVO'), ('mantenimiento', 'MANTENIMIENTO')], null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='resourceType',
            field=models.CharField(choices=[('sala', 'SALA'), ('equipo', 'EQUIPO'), ('espacio', 'ESPACIO')], null=True),
        ),
    ]
