# Generated by Django 6.0.3 on 2026-03-20 20:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0004_remove_resource_resourcetype_alter_resource_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('startAt', models.TimeField()),
                ('endsAt', models.TimeField()),
                ('reason', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('requested', 'Solicitada'), ('confirmed', 'Confirmada'), ('cancelled', 'Cancelada'), ('finished', 'Finalizada')], default='requested', max_length=10)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resource.resource')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
